### PR TITLE
Publish 2.0

### PR DESCRIPTION
**Pull request by nikke234**
Manual testing:
- [x] Windows 10: @Taikelenn 
- [x] Ubuntu: @nikke234  
- [x] Mac: @OlliKiljunen

### CODE REVIEW

**Comment by Taikelenn** [comment]
Manual testing completed on Windows 10 build 19042, with a clean IntelliJ IDEA installation. Remarks:
1.4. Minor nitpick: "Install Scala Plugin by clicking OK." The button is now called "Install":
Screenshot_122

9.11 and 9.12: right-clicking an assignment does not display a context menu.

**Review by Taikelenn — APPROVED** [review]

**Review by nikke234 — COMMENTED** [review]
Works well on Ubuntu 20.04.

Step 0.1 is incorrect.

Number 6 is _very_ long, so we might want to shorten it in some way.

**Comment by OlliKiljunen** [comment]
| Manual test      |                                                          |
| ---------------- | -------------------------------------------------------- |
| Date             | 2021-01-18                                               |
| Operating system | macOS Catalina                                           |
| IDEA version     | 2020.3.1 CE                                              |
| Plugin version   | 2.0 (pre-release)                                        |
| Tester           | Olli                                                     |
| Note             | -                                                        |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

There should be instructions on how to clean the keyring before/after testing.

- **0.1** Version should be 2020.3.x.

- **0.1.B** Outdated instructions.

- **0.2** Instructions should point to: **Customize** > **Color theme** >
          **IntelliJ Light**.

- **0.3** Remove word **Configure** from instructions.

- **1.1** Same as above.

- **4.6** Instructions could mention that a new dialog window opens.

- **4.9** Screenshot from a wrong state (checkbox disabled, dark theme).

- **4.15** **REMARK.** Language should be pre-filled at this stage.

- **9.3** Instructions should not speak of **Modules** "tab".

- **9.9** Instructions should say: "Click **Cancel**".

- **9.12** Same as above.

- **11.2** Instruction redundant with **10.2**.

**Review by OlliKiljunen — APPROVED** [review]
No problems. :) Testing instructions could be updated here and there.

**Pull request merged**
