### PR TITLE
Fix mac ui tests

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

+ Turns out there's a search everywhere button

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [ ] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>e2e</b> tests created</li>
        <li>- [x] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

**Review by nikke234 — APPROVED** [review]
This feels better than changing the keymap :smile: Why click it twice?

**Comment by jaakkonarhi** [comment]
I dunno clicking it once didn't work for the first click

**Comment by nikke234** [comment]
Okay that ...... makes perfect sense :upside_down_face:

**Review by Taikelenn — APPROVED** [review]
I like short pull requests

**Pull request merged**
