### PR TITLE
Filtering UI test

### PR DESCRIPTION
**Pull request by Taikelenn**
# Description of the PR
Related to #500.

This implements tests for filtering assignments. For now the tests do not pass on CI because setting A+ token is not yet merged to master. It does work locally, though. Will convert from draft to a regular pull request once the aformentioned feature is merged.

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [x] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] new <b>e2e</b> tests created</li>
        <li>- [x] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

**Comment by nikke234** [comment]
It would be easier to review this without the conflicts, as it then wouldn't contain all those duplicated changes :wink:

**Review by nikke234 — APPROVED** [review]
Nice! Not a problem but an observation: when running the test, it seemed like some search test still occurred after the filtering tests.

**Comment by nikke234** [comment]
> > Nice! Not a problem but an observation: when running the test, it seemed like some search test still occurred after the filtering tests.
> 
> The filtering test uses searching as a way to quickly expand a week and select a matching assignment by name (it's kind of a bypass for the fact that JTreeFixture does not exist and I don't know how to expand individual tree nodes)

... alright :joy:

**Review by stellatsv — APPROVED** [review]
Nice work!

**Pull request merged**
