### PR TITLE
Buttons on IDE activity popups for free-range tasks

### PR DESCRIPTION
**Pull request by Taikelenn**
# Description of the PR

+ Adds optional action buttons to the IDE activity popups. Currently used only by free-range tasks
+ Adds a new optional field in the IDE activity JSON configuration file "freeRange" (default: false)

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>e2e</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [X] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [X] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>e2e</b> tests created</li>
        <li>- [X] all <b>e2e</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [X] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](https://github.com/Aalto-LeTech/intellij-plugin/blob/master/TESTING.md) or other relevant documentation on _your_ branch?

- [ ] Yes.
- [ ] Not yet. I will do it next.
- [x] Not relevant.

### CODE REVIEW

**Review by OlliKiljunen — COMMENTED** [review]
I added myself as a reviewer only to notice there wasn't any changes after my own contribution. :)

**Review by jaakkonarhi — APPROVED** [review]
Works well

**Review by OlliKiljunen — APPROVED** [review]
Good! :+1: Just curious: when using null actions, is `action` in JSON null or string `"null"` or either?

**Comment by Taikelenn** [comment]
> 
> 
> Good! 👍 Just curious: when using null actions, is `action` in JSON null or string `"null"` or either?

It is `"null"`, not `null`

**Pull request merged**
