### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

+ New logo

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [ ] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [ ] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](/TESTING.md) or other relevant documentation?

- [ ] Yes
- [ ] Not yet. I will do it next.
- [x] Not relevant

### CODE REVIEW

**Comment by Atlanex** [comment]
image
I'm leaning more towards having the pink part fully on top, what do you think? It's easier to have a thick version of and looks good

**Comment by Atlanex** [comment]
image
Here's variations for comparison, current one is the 4th

**Comment by Atlanex** [comment]
image
Here is the thick version in the ui

**Comment by jsorva** [comment]
I like the new logos! I like the old logo, too, though. But let's go with the new one (the thinner version) in 2021, I'd say.

**Comment by superseacat** [comment]
hey, I like the new logo concepts too, shall we give this a go before/after the start of S2? @Aalto-LeTech/idea-plugin-dev @oseppala @jsorva

**Comment by jsorva** [comment]
Go ahead, AFAIC.

**Review by OlliKiljunen — APPROVED** [review]

**Comment by jaakkonarhi** [comment]
image

**Comment by jaakkonarhi** [comment]
image

**Comment by jaakkonarhi** [comment]
Created new pr #473

**Pull request closed without merging**
