### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by nikke234**

### CODE REVIEW

**Review by Taikelenn — CHANGES_REQUESTED** [review]
Please make your name in bold font in the acknowledgement section

**Comment by nikke234** [comment]
> Please make your name in bold font in the acknowledgement section

:joy:

**Comment by nikke234** [comment]
> Please make your name in bold font in the acknowledgement section

This crucial consistency issue has now been fixed, thanks for pointing it out

**Review by Taikelenn — APPROVED** [review]
Farewell

**Review by OlliKiljunen — APPROVED** [review]

**Pull request merged**
