### PR TITLE
Migrate to Java 11

### PR DESCRIPTION
**Pull request by nikke234**
Yes, it is this easy

### CODE REVIEW

**Comment by OlliKiljunen** [comment]
Is this in line with our `since-build` compatibility clause in `plugin.xml`?

**Comment by nikke234** [comment]
Our `since-build` is set to 203. Quoting from [here](https://blog.jetbrains.com/platform/2020/09/intellij-project-migrates-to-java-11/):
> What does it mean for you? If you develop a plugin, you can use new language features and APIs from Java 11, but only if the since-build attribute in plugin.xml is set to 203. If your plugin distribution needs to run on multiple versions of the IDE, for example 202 and 203, then you should remain on Java 8.

TL;DR: yes

**Review by OlliKiljunen — APPROVED** [review]
👍

**Review by jaakkonarhi — APPROVED** [review]
great

**Comment by superseacat** [comment]
and what about the modularization from Java 9 @nikke234 https://apluslms.slack.com/archives/CSDV9CA31/p1613045743037700 ?

**Comment by superseacat** [comment]
```kotlin
compileE2eKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
    }
}
```
should we change this in any way? does it compile still with the existing option?

**Comment by OlliKiljunen** [comment]
@superseacat said:
> 
> and what about the modularization from Java 9 @nikke234 https://apluslms.slack.com/archives/CSDV9CA31/p1613045743037700 ?

AFAIK, defining modules is optional; you don't have to modularize your code only because your using Java 9+. But we should do that in the future as a part of #531, I'd say.

**Review by superseacat — APPROVED** [review]
let's try, I'm leaving soon anyway 😀

**Comment by nikke234** [comment]
> should we change this in any way? does it compile still with the existing option?

Nice catch! They still compile and work as usual, but I guess there is no harm in using 11 there as well (which also works), so I'll change it

**Pull request merged**
