### PR TITLE
Publish 1.2

### PR DESCRIPTION
**Pull request by nikke234**

### CODE REVIEW

**Comment by OlliKiljunen** [comment]
| Manual test      |                                                          |
| ---------------- | -------------------------------------------------------- |
| Date             | 2020-08-26                                               |
| Operating system | Windows 10                                               |
| IDEA version     | 2020.2.1 CE                                              |
| Plugin version   | 1.2 (pre-release)                                        |
| Tester           | Olli                                                     |
| Note             | -                                                        |

When the software doesn't comply with the testing manual...

| ...it is marked with... | ...if the reason for the incompliance is that...  |
| ----------------------- | ------------------------------------------------- |
| **FAILED!!!**           | there's a bug in the software.                    |
| **REMARK.**             | the software should (perhaps) be changed.         |
| normal                  | the testing manual should be changed.             |

### Notes

- **1.4** This assertion should come after **1.5**.

- **2.1** The button is now just **New Project**.

- **2.5** Move this after 2.10.

- **3.1** The menu item is now called **About the A+ Courses Plugin**.

- **3.5** What to do with the browser window?

- **4.7** Instructions should tell which language to select.  Outdated screenshot.

- **4.9** There should be instruction to open the tool window.

- **4.10** **FAILED!!!**  **O1Library** is marked **[Double-click to install]**.

- **4.12** **REMARK.** Language must be selected first.

- **6.6** Outdated screenshot.

- **6.25** This would fit better after **6.26**.

- **6.40** There could be hint to use **File** menu to easily restart.

- **6.41** The file must be from a module that compiles, e.g. **O1Library**.

- **6.46** See previous.

- **7.5** Should assert also that the status changes to **Installed**.

**Review by OlliKiljunen — COMMENTED** [review]
There was one failing assertion in manual testing on windows (see my previous comment). But as it is a minor thing. I approve.

**Review by OlliKiljunen — APPROVED** [review]
Yeah.

**Review by superseacat — APPROVED** [review]
works with a minor issue as @OlliKiljunen brought up

**Pull request merged**
