### PR TITLE
Submit with ctrl-click

### PR DESCRIPTION
**Pull request by jaakkonarhi**
# Description of the PR

Ctrl + left clicking an assignment opens the submission window. Also works when clicking submissions, which I think is fine. Part of #248 

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [ ] new <b>unit</b> tests created</li>
        <li>- [x] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](/TESTING.md) or other relevant documentation?

- [ ] Yes
- [x] Not yet. I will do it next.
- [ ] Not relevant

### CODE REVIEW

**Comment by jaakkonarhi** [comment]
Only the last commit is relevant

**Comment by OlliKiljunen** [comment]
Can you link to the issue this is related to?

**Comment by jaakkonarhi** [comment]
From the comments of #248

**Comment by jaakkonarhi** [comment]
Accidents happened

**Pull request closed without merging**
