### PR TITLE
Add submission count and points to exercise list

### PR DESCRIPTION
**Pull request by nikke234**
# Description of the PR

Adds submission count and points to the exercise list, as well as some useful tooltip texts.

# Testing
<table>
  <tr>
    <th>unit</th>
    <th>integration</th>
    <th>manual</th>
  </tr>
  <tr>
    <td>
      <ul>
        <li>- [x] new <b>unit</b> tests created</li>
        <li>- [x] all <b>unit</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [ ] new <b>integration</b> tests created</li>
        <li>- [x] all <b>integration</b> tests pass</li>
      </ul>
    </td>
    <td>
      <ul>
        <li>- [x] <b>manual</b> testing went well</li>
      </ul>
    </td>
  </tr>
</table>  
  
# Have you updated the [TESTING.md](/TESTING.md) or other relevant documentation?

- [ ] Yes
- [ ] Not yet. I will do it next.
- [x] Not relevant

### CODE REVIEW

**Comment by superseacat** [comment]
cool stuff :sunglasses: 

a couple of questions:
* do you think it would make sense to additionally show also a per-submission data (results), as currently there is no way to tell which of those submissions were good/bad
* is the best or the last submission result is currently being shown for assignment

**Comment by superseacat** [comment]
two submissions out of zero, that give zero points out of zero points and "pass" (green - full points icon)

Screenshot from 2020-08-06 19-57-28

**Comment by nikke234** [comment]
> cool stuff :sunglasses:
> 
> a couple of questions:
> 
>     * do you think it would make sense to additionally show also a per-submission data (results), as currently there is no way to tell which of those submissions were good/bad
> 
>     * is the best or the last submission result is currently being shown for assignment
> 
>     * and a hypothetical one, if a student makes a submission, which is worth 100% points, but it's overdue, so gets -100% points (zero), how is it shown?

Thanks!

To the first question, yes, it would definitely make sense, but it also involves using a different end point and adding caching, so it requires a lot more effort :smile: 

The points should always show the points of the best submission made.

Also, when points are deducted due to a late submission, it should show 0 points, as that would also be the points that the API reports.

**Comment by nikke234** [comment]
> two submissions out of zero, that give zero points out of zero points and "pass" (green - full points icon)
> 
> Screenshot from 2020-08-06 19-57-28

Okay that admittedly looks a bit weird :smile: The training exercises are a bit tricky, as they have `max_points` 0 and `max_submissions` 0. I'll think about a better way to display them

**Comment by superseacat** [comment]
> The training exercises are a bit tricky, as they have `max_points` 0 and `max_submissions` 0. I'll think about a better way to display them

an [image](https://github.com/JetBrains/intellij-plugins/blob/master/ide-features-trainer/res/img/featureTrainerToolWindow.svg) to underline it's a training assignment?

**Comment by superseacat** [comment]
> Also, when points are deducted due to a late submission, it should show 0 points, as that would also be the points that the API reports.

but what would be the icons then: full points, zero points or partial?

**Comment by nikke234** [comment]
> > The training exercises are a bit tricky, as they have `max_points` 0 and `max_submissions` 0. I'll think about a better way to display them
> 
> an [image](https://github.com/JetBrains/intellij-plugins/blob/master/ide-features-trainer/res/img/featureTrainerToolWindow.svg) to underline it's a training assignment?

Yes I think this is the way to go, good idea. Showing the points icons makes no sense anyways, as it will show the full points icon even if the submission is completely incorrect, since you still have 0/0 points :smile:

**Comment by nikke234** [comment]
> > Also, when points are deducted due to a late submission, it should show 0 points, as that would also be the points that the API reports.
> 
> but what would be the icons then: full points, zero points or partial?

I have to verify this, but I'm 99% the icon will also show zero points, so the only way to know that a submission was correct after the deadline

**Comment by nikke234** [comment]
> the code itself is clearly OK!
> 
> could you please extract the ideas we discussed as separate issues (tickets) for the future, and then eventually feel free to merge :1st_place_medal:

Will do :+1:

**Comment by superseacat** [comment]
> > > Also, when points are deducted due to a late submission, it should show 0 points, as that would also be the points that the API reports.
> > 
> > 
> > but what would be the icons then: full points, zero points or partial?
> 
> I have to verify this, but I'm 99% sure the icon will also show zero points, so the only way to know that a submission (after the deadline) was correct, is to actually open the submission and look at the feedback.

if only there would be a way to learn that wo opening the submission :wink:

**Pull request merged**
